Homework2
made-mlops-2022/lyamzin_alexey pull request #2
Opened 2022-11-27 02:40 UTC by AlexGrunt

- [x] Оберните inference вашей модели в rest сервис на FastAPI, должен быть endpoint /predict (3 балла)
- [x] Напишите endpoint /health, который должен возращать 200, если ваша модель готова к работе (такой чек особенно актуален, если делаете доп задание про скачивание из хранилища) (1 балл)
- [x] Напишите unit тест для /predict (https://fastapi.tiangolo.com/tutorial/testing/, https://flask.palletsprojects.com/en/1.1.x/testing/) (3 балла)
- [ ] Напишите скрипт, который будет делать запросы к вашему сервису (2 балла)
- [x] Напишите Dockerfile, соберите на его основе образ и запустите локально контейнер (`docker build`, `docker run`). Внутри контейнера должен запускаться сервис, написанный в предущем пункте. Закоммитьте его, напишите в README.md корректную команду сборки (4 балла)
- [x] Опубликуйте образ в https://hub.docker.com/, используя `docker push` (вам потребуется зарегистрироваться) (2 балла)
- [x] Опишите в README.md корректные команды `docker pull/run`, которые должны привести к тому, что локально поднимется на inference ваша модель. Убедитесь, что вы можете протыкать его скриптом из пункта 3 (1 балл)
- [x] Проведите самооценку - распишите в реквесте какие пункты выполнили и на сколько баллов, укажите общую сумму баллов (1 балл)
 **Дополнительная часть**:
- [x] Ваш сервис скачивает модель из S3 или любого другого хранилища при старте, путь для скачивания передается через переменные окружения (+2 доп балла)
- [ ] Оптимизируйте размер docker image. Опишите в README.md, что вы предприняли для сокращения размера и каких результатов удалось добиться. Должно получиться мини исследование -- я сделал тото и получился такой-то результат (+2 доп балла)
- [x] Сделайте валидацию входных данных https://pydantic-docs.helpmanual.io/usage/validators/ . Например, порядок колонок не совпадает с трейном, типы, допустимые максимальные и минимальные значения. Проявите фантазию, это доп. баллы, проверка не должна быть тривиальной. Вы можете сохранить вместе с моделью доп информацию о структуре входных данных, если это нужно (+2 доп балла). https://fastapi.tiangolo.com/tutorial/handling-errors/ -- возращайте 400, в случае, если валидация не пройдена

# Итого: 19 баллов

2022-12-25 14:54 UTC, nickdndev requested changes

2022-12-25 14:54 UTC, nickdndev commented on online_inference/app/crud.py
> +def healthcheck(pipeline: Union[Pipeline, None]):
для это есть  optional
```
Union[Pipeline, None]-> optional[Pipeline]
```

2022-12-25 14:54 UTC, nickdndev commented on online_inference/app/main.py
> +    return crud.healthcheck(pipeline)
k8s обстукивает регулярно и не надо делать предикт каждый раз даже есть это с пустыми данными.

тут надо добавить, что модель загрузилась нормально и каждый раз возращать true (200 code)

2022-12-25 14:54 UTC, nickdndev commented on online_inference/app/main.py
> +    # except HTTPException as err:
используете ? если нет , то удалить

2022-12-25 14:54 UTC, nickdndev commented on online_inference/app/main.py
> +# import schemas
удалить

2022-12-25 14:54 UTC, nickdndev commented on online_inference/src/models/model.py
> +    def predict(self, X):
добавить typing

2022-12-29 20:07 UTC, AlexGrunt commented
Внес изменения

2022-12-30 15:26 UTC, nickdndev commented
итог:19

2022-12-30 15:26 UTC, nickdndev approved these changes

2022-12-30 21:00 UTC, merged